### ISSUE TITLE
使用isic数据集跑出来效果很奇怪

### ISSUE THREAD

**Issue by erlingzz** [WuJunde/MedSegDiff#104]
你好，我使用isic数据集训练模型，大约跑了20w个step，测试时num_ensemble设置为1，部分生成的分割图很奇怪，如下（左为gt，右为测试结果）：
![image](https://github.com/WuJunde/MedSegDiff/assets/95128580/65f60a5a-2611-436f-a01a-b619ba3ac6ee)

请问这是正常的情况嘛？

**Comment by GuoHuike7** [comment]
20w轮训了多久呀，我这采样一张2分钟

**Comment by GuoHuike7** [comment]
加你qq了，方便通过一下嘛

**Comment by erlingzz** [comment]
> 



> don't sample 1 time, ensemble is very important for the performance. but this result is unexpectedly bad for even 1 sample.

Thank you for your answer. Could you please tell me how many steps you ran on the ISIC dataset, and what the final iou and dice are?

**Comment by ValeriaLiu** [comment]
> > 
> 
> 20w step about 89% dice in my workplace

I work on my own dataset and I find that as the steps increase, the train loss will not change significantly but the prediction's accuracy of the model will increase. Have you ever encountered such a similar situation? 
Look forward to your reply.

**Comment by WuJunde** [comment]
yes, it happens. train more until it stuck
