### ISSUE TITLE
如果我只有一块显卡的话也可以直接用吗，我看代码都是分布式的代码，还是可以把分布式改一下？

### ISSUE THREAD

**Issue by yuan5828225** [WuJunde/MedSegDiff#108]

**Comment by WuJunde** [comment]
no need to modify, run in default for single gpu, set -multi_gpu parameter for multiple gpu

**Comment by yuan5828225** [comment]
> no need to modify, run in default for single gpu, set -multi_gpu parameter for multiple gpu
Thank you for your answer
