### ISSUE TITLE
Loading custom MRI datasets

### ISSUE THREAD

**Issue by aalhayali** [WuJunde/MedSegDiff#13]
Hi!

Thanks for this repo, really exciting stuff!

I have a sagittal MRI dataset that has the following dimensions:  `(512,512,7)` `(H, W, Slice)` in NIFTI format. How should the input be for the network to train? In my understanding, since the autoencoder is 2D U-Net, the networks will be trained on each slice of each patient individually, however, I'm a bit confused about the input to network should be.

**Comment by WuJunde** [comment]
In fact, you can train it in anyway you like. For example, you can even change it to 3D-UNet-like architecture and train on the volume. But in my given example of BraTs, I input a slice with [bachsize, channels, H, W], the channels are  ['t1', 't1ce', 't2', 'flair'].

**Comment by aalhayali** [comment]
Oh that's cool! I'll give it a shot later. btw - would you be interested in incorporating MONAI into data loading? I'll be trying that just so that the code is less verbose.

**Comment by WuJunde** [comment]
That sounds awesome! I love MONAI, I would be really grateful if you could contribute MONAI data loading to this repo. I'm currently working on a few other things, like a version for use in resource-limited environments and trying to make inferences more user-friendly, so I don't think our updates will overlap. Feel free to go ahead if you're interested.

**Comment by aalhayali** [comment]
Beauty! I'll get working on that. I think a <5 lines data loading pipeline would be very valuable.
