### ISSUE TITLE
Questions about the forward function of the UNetMode 

### ISSUE THREAD

**Issue by NiAn-creator** [WuJunde/MedSegDiff#15]
Dear authors:

I have some questions about the function of the highway_forward (Generic_UNet). Detailed as follows:
1)	On the ISIC dataset, the resolution of the input image is [batch, 3, 64, 64], which means that c is [batch, 3, 64, 64]. But the hs[12] is out of range, so we have changed the index as 2, 5, 8, and 11, corresponding to the resolution of […,64,64], […,32,32], […,16,16], and […,8,8], respectively. This operation is right?
2)	The h and hb on L768 have different resolutions. Should it be resized?
<img width="416" alt="image" src="https://user-images.githubusercontent.com/37520589/209085708-02d92eb2-9af3-490b-8149-9092013348de.png">

3)	When calculating the x=x*ha*hb in froward function of the Generic_UNet, x, ha, and hb have different resolution. Should it be resized?
<img width="416" alt="image" src="https://user-images.githubusercontent.com/37520589/209085671-e325fc92-d93c-499b-a61c-62e67105ad6f.png">

I hope for your response sincerely. Thanks a lot!

**Comment by WuJunde** [comment]
you may want to check this issue: https://github.com/WuJunde/MedSegDiff/issues/8

**Comment by NiAn-creator** [comment]
Thanks for your suggestion!
I have another question. If the segmentation_sample.py lacks a termination condition? Because the all_images always is None (Given on Line 71 and Line 91).

**Comment by WuJunde** [comment]
The current setting will run on all test images. You can modify 'all_images' if you want to run on a part of test images controlled by 'num_samples' parameter.

**Comment by NiAn-creator** [comment]
Thanks!  I have got it.
