### ISSUE TITLE
problems during training

### ISSUE THREAD

**Issue by jessie-chen99** [WuJunde/MedSegDiff#16]
![image](https://user-images.githubusercontent.com/62527700/209553477-9c6ca097-81d2-4e32-9046-9af64cf426bf.png)

https://github.com/WuJunde/MedSegDiff/blob/efd1ece0f8323b68aa1d319ce5abbe49c5955864/guided_diffusion/dpm_solver.py#L1257

HIi, thanks for your great work! 😊 Could you tell me how to use this part of code?  Can I just use “return v[(...,) + (None,)*(dims - 1)]”  to replace line1257-1261? 

My programming ability is not very good so I cannot understand this part. Why did you write this part like this? Looking forward to your reply!!

**Comment by WuJunde** [comment]
sorry, sth wrong when i upload the code. it has been solved
