### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by ZhouCX117** [WuJunde/MedSegDiff#17]
Hi, could you please provide your pre-trained models? I train a model, but the sampling result is not right. The max value of the pixel is about 10, so the pictures are all black.

**Comment by WuJunde** [comment]
it's nothing to do with the weight. Do you modify sth in the code? someone had the same question: https://github.com/WuJunde/MedSegDiff/issues/6.

**Comment by ZhouCX117** [comment]
Thanks for your reply! What does the sth mean? I don't revise any code and run the code following the instructions in the readme.

**Comment by WuJunde** [comment]
have u solved the problem? I checked the code again and the output will definitely be 0-1. Make sure you use the last version of the code and the results are those automatically saved in ./results folder.
