### ISSUE TITLE
training&inference time cost

### ISSUE THREAD

**Issue by jessie-chen99** [WuJunde/MedSegDiff#21]
Hi! I am tring to use your code on BRATS2020 with sliced input image. 

If I follow README and use this command on one single 3090GPU(24G), what is the correct time cost?  

![image](https://user-images.githubusercontent.com/62527700/211522085-48a0e03b-d164-4a0e-a39d-13e38aa0b62e.png)

btw, could you please share one of your training log as an example? many thx!!

**Comment by WuJunde** [comment]
I never trained it on a single 3090GPU, so I don't know the exact time. Using the default parameters, it may cost 3 to 4 days for a complete training, 1 or 2 minuts for one test sample. It really depends on your expectation of performance, e.g., the second or the third training day may improve slightly,  less ensemble/DPM-solver can speed up inference but with performance compromise

**Comment by jessie-chen99** [comment]
Thanks! 

"1 or 2 minuts for one test sample", here "one test sample" is a slice or a volume(of a patient)?

And could you share the test code of saving niii.gz files which are needed to upload to BraTS2020 official website? I cannot find this part in related source code so I don't know how to get the test score of trained model.😥
