### ISSUE TITLE
Why the DPM solver is only used in sampling but not training?

### ISSUE THREAD

**Issue by caihaunqai** [WuJunde/MedSegDiff#25]
Hello, I found that the DPM solver can only be found in the function p_sample_loop_known. But I can not find them in training codes. Can you tell me?

**Comment by WuJunde** [comment]
DPM solver is used for sampling/inference, not for training. see their paper for more details: https://arxiv.org/abs/2206.00927

**Comment by caihaunqai** [comment]
Thank you. I want to know how to release the memory since it keep increasing.

**Comment by WuJunde** [comment]
it's a bug caused by pytorch version, see this issue: https://github.com/WuJunde/MedSegDiff/issues/23

**Comment by caihaunqai** [comment]
Thank you!
