### ISSUE TITLE
Why there are some unused parameters?

### ISSUE THREAD

**Issue by caihaunqai** [WuJunde/MedSegDiff#27]
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss.

**Comment by WuJunde** [comment]
it did not happen in my workplace. it looks like you define some parameterized layer in 'class NetWorkxx: def __init__' but not used in the forward

**Comment by caihaunqai** [comment]
Thank you~

**Comment by ValeriaLiu** [comment]
Hello，I have the same problem as you.  Have you solved the problem now?
