### ISSUE TITLE
When will the training stop?

### ISSUE THREAD

**Issue by caihaunqai** [WuJunde/MedSegDiff#28]
Thank you for your excellent job. I wonder how many iterations will be used for training since I do not find the condition to stop training. Thank you.

**Comment by WuJunde** [comment]
it depends on you. I did not set a hard condition because converge num of steps vary a lot for different datasets. Generally speaking, 100,000 steps will be enough for most of the datasets.

**Comment by caihaunqai** [comment]
Thank you~

**Comment by zhao9chen99999** [comment]
i wonder where could set the number of epoch？
