### ISSUE TITLE
Problem of dimension

### ISSUE THREAD

**Issue by sutiankang** [WuJunde/MedSegDiff#3]
I am curious that why the model output channel dimension is 2, my output is [b image_size image_size], but your code need output [b 2 image_size image_size].
![image](https://user-images.githubusercontent.com/61399929/205476329-bf66d857-24e3-4b08-864c-dc291e7cf115.png)

**Comment by WuJunde** [comment]
two channels represent mean and variance

**Comment by sutiankang** [comment]
> two channels represent mean and variance

Thanks! I think that if len(model_output) == 2 can be revised as if isinstance(model_output, tuple). Because I find when training process model_output is a Tensor but sample process is a tuple.

**Comment by WuJunde** [comment]
> > two channels represent mean and variance
> 
> Thanks! I think that if len(model_output) == 2 can be revised as if isinstance(model_output, tuple). Because I find when training process model_output is a Tensor but sample process is a tuple.

Good, I have updated. Many temporary/lazy implementations in the code. Welcome to point out.

**Comment by sutiankang** [comment]
> > > two channels represent mean and variance
> > 
> > 
> > Thanks! I think that if len(model_output) == 2 can be revised as if isinstance(model_output, tuple). Because I find when training process model_output is a Tensor but sample process is a tuple.
> 
> Good, I have updated. Many temporary/lazy implementations in the code. Welcome to point out.

Thanks. I have another question to consult about the meaning of 3 in the following image. Whether to represent the channel of the conditional image such as the channel dimension of RGB image. When my conditional image channel is 6, do I need to change it to 6.

![image](https://user-images.githubusercontent.com/61399929/205480665-36fec140-ce66-4afd-82e8-1b8abc701721.png)

**Comment by WuJunde** [comment]
> > > > two channels represent mean and variance
> > > 
> > > 
> > > Thanks! I think that if len(model_output) == 2 can be revised as if isinstance(model_output, tuple). Because I find when training process model_output is a Tensor but sample process is a tuple.
> > 
> > 
> > Good, I have updated. Many temporary/lazy implementations in the code. Welcome to point out.
> 
> Thanks. I have another question to consult about the meaning of 3 in the following image. Whether to represent the channel of the conditional image such as the channel dimension of RGB image. When my conditional image channel is 6, do I need to change it to 6.
> 
> ![image](https://user-images.githubusercontent.com/61399929/205480665-36fec140-ce66-4afd-82e8-1b8abc701721.png)

It should be your channels + 1. This parameter will not be used in this version of code though.

**Comment by sutiankang** [comment]
> 

Thanks a lot for your help！

**Comment by sutiankang** [comment]
> > > > > two channels represent mean and variance
> > > > 
> > > > 
> > > > Thanks! I think that if len(model_output) == 2 can be revised as if isinstance(model_output, tuple). Because I find when training process model_output is a Tensor but sample process is a tuple.
> > > 
> > > 
> > > Good, I have updated. Many temporary/lazy implementations in the code. Welcome to point out.
> > 
> > 
> > Thanks. I have another question to consult about the meaning of 3 in the following image. Whether to represent the channel of the conditional image such as the channel dimension of RGB image. When my conditional image channel is 6, do I need to change it to 6.
> > ![image](https://user-images.githubusercontent.com/61399929/205480665-36fec140-ce66-4afd-82e8-1b8abc701721.png)
> 
> It should be your channels + 1. This parameter will not be used in this version of code though.

Thanks a lot for your help！
