### ISSUE TITLE
Question about the mse loss for training segmentation tasks

### ISSUE THREAD

**Issue by JingyeChen** [WuJunde/MedSegDiff#38]
Thanks for your great work and your effort on sharing this code. Here I am wondering that, is it stable to use mse loss for training segmentation tasks? Usually we use cross-entropy loss to train this task and this is what i am curious about.

Thanks for reading this issue and I am looking forward to your reply!

**Comment by WuJunde** [comment]
Hi, very interesting question. We find ce loss perform far worse than mse in our case. After checking the results, we find ce loss causes  many 'low' values after STAPLE ensemble ( for example, most values range from 0-0.1 in the normalized results). Any idea what is happening here? Maybe there has sth we can delve into. Feel free to contact me by email: jundewu@ieee.org.
