### ISSUE TITLE
V2版本代码什么时候公布

### ISSUE THREAD

**Issue by theneao** [WuJunde/MedSegDiff#46]
对于扩散做语义分割给予了厚望，但用在自己的数据集V1的代码结果不太理想，希望能够尽早发布V2版本

**Comment by AnthonyHaozeZhu** [comment]
您好，方便一起交流一下吗

**Comment by theneao** [comment]
已经私信你邮箱，请查看

**Comment by theneao** [comment]
> 您好，方便一起交流一下吗

已经私信你邮箱，请查看

**Comment by MaggieLSY** [comment]
> 对于扩散做语义分割给予了厚望，但用在自己的数据集V1的代码结果不太理想，希望能够尽早发布V2版本

Me too, looking forward to MedSegDiffV2 code.

**Comment by pqu2** [comment]
在文件unet.py中的Class UNetModel，在forward部分uemb, cal = self.highway_forward(c, [hs[3],hs[6],hs[9],hs[12]])这里的12超出下标界限了吧，要怎么改？

**Comment by cyz21** [comment]
> 
我也遇到了这个问题 怎么办呢？

**Comment by cyz21** [comment]
> 在文件unet.py中的Class UNetModel，在forward部分uemb, cal = self.highway_forward(c, [hs[3],hs[6],hs[9],hs[12]])这里的12超出下标界限了吧，要怎么改？

我也遇到了这个问题 怎么办呢？

**Comment by TMullerSG** [comment]
> > 在文件unet.py中的Class UNetModel，在forward部分uemb, cal = self.highway_forward(c, [hs[3],hs[6],hs[9],hs[12]])这里的12超出下标界限了吧，要怎么改？
> 
> 我也遇到了这个问题 怎么办呢？

要把图像改成256,channel 128

**Comment by jaceqin** [comment]
> 对于扩散做语义分割给予了厚望，但用在自己的数据集V1的代码结果不太理想，希望能够尽早发布V2版本

你好 方便请教你一下吗

**Comment by zzh1230** [comment]
> 对于扩散做语义分割给予了厚望，但用在自己的数据集V1的代码结果不太理想，希望能够尽早发布V2版本

您好 请问是否方便请教您一些问题

**Comment by theneao** [comment]
留联系方式，或者点我头像，发我邮箱

**Comment by theneao** [comment]
有问题需要讨论的，点我头像，发我邮箱

**Comment by knavecoder** [comment]
> > > 在文件 unet.py 中的Class UNetModel，在forward部分uemb， cal = self.highway_forward（c， [hs[3]，hs[6]，hs[9]，hs[12]]）这里的12超出下标界限了吧，要怎么改？
> > 
> > 
> > 我也遇到了这个问题 怎么办呢？
> 
> 要把图像改成256，channel 128

在训练时调用 batch, cond, name = next(data_iter)，显示没有住够多的值怎么办

**Comment by knavecoder** [comment]
script_util.py的run_loop中batch, cond, name = next(data_iter)这里没有足够值给调用，要怎么修改

**Comment by theneao** [comment]
> 
guided_diffusion/isicloader.py  54行
dataloader文件里 最后train的时候return的少了，加上就行
