### ISSUE TITLE
the hyperparameters setting issue

### ISSUE THREAD

**Issue by wenyihan4396** [WuJunde/MedSegDiff#47]
Thank you for you great job!

Can I leverage these parameters "**--diffusion_steps 50 --dpm_solver True** " in training process?

请问**--diffusion_steps 50 --dpm_solver True**的参数设置可以被用于training过程中吗？
还是他们只能被用于sampling过程？

**Comment by WuJunde** [comment]
only for sampling

文翊涵 ***@***.***> 于2023年3月7日周二 13:38写道：

**Comment by wenyihan4396** [comment]
感谢您的回答
