### ISSUE TITLE
Problems of traing

### ISSUE THREAD

**Issue by jaceqin** [WuJunde/MedSegDiff#5]
I encountered the following problems when training with BRATS dataset！Can you help me？Thanks！

 File "D:\jace\pythonProject\MedSegDiff-master\MedSegDiff-master\guided_diffusion\train_util.py", line 83, in __init__
    self._load_and_sync_parameters()
  File "D:\jace\pythonProject\MedSegDiff-master\MedSegDiff-master\guided_diffusion\train_util.py", line 139, in _load_and_sync_parameters
    dist_util.sync_params(self.model.parameters())
  File "D:\jace\pythonProject\MedSegDiff-master\MedSegDiff-master\guided_diffusion\dist_util.py", line 76, in sync_params
    dist.broadcast(p, 0)
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

**Comment by WuJunde** [comment]
have you modified anything in the code?

**Comment by litlepeng** [comment]
Directly training on the BraTS20 dataset, the following error was reported, please answer the author thank you.

**Comment by litlepeng** [comment]
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/29767470/209474974-39bd7dbb-16f3-4995-9e06-8fc7e43df591.png">

**Comment by litlepeng** [comment]
I directly trained on the BraTS20 dataset and reported the following error. Please help me answer it. Thank you.
<img width="1682" alt="image" src="https://user-images.githubusercontent.com/29767470/209475028-89a69c81-d785-4336-889d-361f13c318bc.png">

**Comment by WuJunde** [comment]
It processes each slice individually, you should input a slice with the shape [8,5,256,256].

**Comment by litlepeng** [comment]
I directly used the BraTS20 dataset for training, now how do I need to modify it specifically, thank you

**Comment by WuJunde** [comment]
you need to extract each slice from a volume for training. you can also download brats20 dataset with slice format from kaggle

**Comment by litlepeng** [comment]
Would it be convenient for you to put a link? I also could not find the sliced brats20 dataset on kaggle. Thank you very much

**Comment by litlepeng** [comment]
Thank you. I'll try again.

**Comment by litlepeng** [comment]
The brats20 of this slice is in h5 format, and it is not consistent with the data sets t1, t1ce, t2, flair that you need. Now do you need to change the bratsloard.py file name yourself? Could you please provide your dataset directly? Thank you very much。
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/29767470/209685893-70c70bec-d9ec-4ae0-b1b1-ab27ee600e28.png">
<img width="967" alt="image" src="https://user-images.githubusercontent.com/29767470/209686141-8997edbe-a20a-49e4-9c15-fa4f834f8222.png">

**Comment by WuJunde** [comment]
hi, in fact, you can simply extract the slices from volume through two lines code like:
for index in range(volume.size(2)):
    slice = volume[:,:,index,:,:]
ps: MedSegDiff is not a good project for you to start in this field, a recomment route is unet->nnunet->transunet->medsegdiff.

**Comment by litlepeng** [comment]
Thank you for your advice
