### ISSUE TITLE
Model'difference when I run segmentation_sample.py

### ISSUE THREAD

**Issue by ValeriaLiu** [WuJunde/MedSegDiff#50]
Excellent work!
I'm a beginner in the field of deep learning.
I have a question that when I run segmentation_sample.py, what's the difference between savedmodel_XXXX.pt, optsavedmodel_XXXX.pt, emasavedmodel_XXXX.pt.
Thanks a lot.

**Comment by cyz21** [comment]
> Excellent work! I'm a beginner in the field of deep learning. I have a question that when I run segmentation_sample.py, what's the difference between savedmodel_XXXX.pt, optsavedmodel_XXXX.pt, emasavedmodel_XXXX.pt. Thanks a lot.

Have you solved it? I also have this question. thank you.

**Comment by ValeriaLiu** [comment]
> > Excellent work! I'm a beginner in the field of deep learning. I have a question that when I run segmentation_sample.py, what's the difference between savedmodel_XXXX.pt, optsavedmodel_XXXX.pt, emasavedmodel_XXXX.pt. Thanks a lot.
> 
> Have you solved it? I also have this question. thank you.

Sorry, I haven't solved it .

**Comment by iYeekk** [comment]
> Excellent work! I'm a beginner in the field of deep learning. I have a question that when I run segmentation_sample.py, what's the difference between savedmodel_XXXX.pt, optsavedmodel_XXXX.pt, emasavedmodel_XXXX.pt. Thanks a lot.

Have you solved it? I have the same doubt, thanks!

**Comment by WuJunde** [comment]
check this issue: https://github.com/WuJunde/MedSegDiff/issues/61
