### ISSUE TITLE
No dpm_solver Error during inference/sampling

### ISSUE THREAD

**Issue by Saharsh1005** [WuJunde/MedSegDiff#55]
### **Question**
After running training on custom dataset, the ./results/ folder produced models of these three types: 
1. `/kaggle/input/medsegdiff-trials/results/emasavedmodel_0.9999_040000.pt`
2. `/kaggle/input/medsegdiff-trials/results/optsavedmodel040000.pt`
3. `/kaggle/input/medsegdiff-trials/results/savedmodel040000.pt`

For inference, in the model_path argument, which checkpoint should I provide? I am not clear about what each of them signifies.

 ### **References**
**Training Logs:**
Last check-point:
```
--------------------------
| grad_norm   | 2.13     |
| loss              | 0.0117   |
| loss_cal        | 0.00869  |
| loss_cal_q0  | 0.00925  |
| loss_cal_q1  | 0.00853  |
| loss_cal_q2  | 0.00879  |
| loss_cal_q3  | 0.00816  |
| loss_q0        | 0.0419   |
| loss_q1        | 0.00343  |
| loss_q2        | 0.00113  |
| loss_q3        | 0.000812 |
| mse_diff      | 0.0117   |
| mse_diff_q0 | 0.0419   |
| mse_diff_q1 | 0.00343  |
| mse_diff_q2 | 0.00113  |
| mse_diff_q3 | 0.000812 |
| param_norm  | 263      |
| samples       | 7.16e+04 |
| step             | 1.79e+04 |
--------------------------
```

**Error during inference:**
Note: For all the three modeltypes I am getting this error " No dpm-solver".
```
Logging to ./results/
creating model and diffusion...
sampling...
no dpm-solver
```

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_23/238904562.py in <module>
    206 
    207 if __name__ == "__main__":
--> 208     main()

/tmp/ipykernel_23/238904562.py in main()
    162                 step = args.diffusion_steps,
    163                 clip_denoised=args.clip_denoised,
--> 164                 model_kwargs=model_kwargs,
    165             )
    166 

/kaggle/input/codebase-medsegdiff/MedSegDiff-master/guided_diffusion/gaussian_diffusion.py in p_sample_loop_known(self, model, shape, img, step, org, noise, clip_denoised, denoised_fn, cond_fn, model_kwargs, device, progress, conditioner, classifier)
    569                 model_kwargs=model_kwargs,
    570                 device=device,
--> 571                 progress=progress,
    572             ):
    573                 final = sample

/kaggle/input/codebase-medsegdiff/MedSegDiff-master/guided_diffusion/gaussian_diffusion.py in p_sample_loop_progressive(self, model, shape, time, noise, clip_denoised, denoised_fn, cond_fn, org, model_kwargs, device, progress)
    638                         clip_denoised=clip_denoised,
    639                         denoised_fn=denoised_fn,
--> 640                         model_kwargs=model_kwargs,
    641                     )
    642                     yield out

/kaggle/input/codebase-medsegdiff/MedSegDiff-master/guided_diffusion/gaussian_diffusion.py in p_sample(self, model, x, t, clip_denoised, denoised_fn, model_kwargs)
    444             clip_denoised=clip_denoised,
    445             denoised_fn=denoised_fn,
--> 446             model_kwargs=model_kwargs,
    447         )
    448         noise = th.randn_like(x[:, -1:,...])

/kaggle/input/codebase-medsegdiff/MedSegDiff-master/guided_diffusion/respace.py in p_mean_variance(self, model, *args, **kwargs)
     88         self, model, *args, **kwargs
     89     ):  # pylint: disable=signature-differs
---> 90         return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
     91 
     92     def training_losses(

/kaggle/input/codebase-medsegdiff/MedSegDiff-master/guided_diffusion/gaussian_diffusion.py in p_mean_variance(self, model, x, t, clip_denoised, denoised_fn, model_kwargs)
    320             else:
    321                 pred_xstart = process_xstart(
--> 322                     self._predict_xstart_from_eps(x_t=x, t=t, eps=model_output)
    323                 )
    324             model_mean, _, _ = self.q_posterior_mean_variance(

/kaggle/input/codebase-medsegdiff/MedSegDiff-master/guided_diffusion/gaussian_diffusion.py in _predict_xstart_from_eps(self, x_t, t, eps)
    342 
    343     def _predict_xstart_from_eps(self, x_t, t, eps):
--> 344         assert x_t.shape == eps.shape
    345         return (
    346             _extract_into_tensor(self.sqrt_recip_alphas_cumprod, t, x_t.shape) * x_t

AssertionError:
```

**Inference configuration**
```
def create_argparser():
    defaults = dict(
        data_name = 'NUCLEI',
        data_dir="./kmms_test/kmms_test",
        clip_denoised=True,
        num_samples=1,
        batch_size=1,
        use_ddim=False,
        model_path="", # Here I gave the model paths
        num_ensemble=5,      #number of samples in the ensemble
        gpu_dev = "0",
        out_dir='./results/',
        multi_gpu = None, #"0,1,2",
        dpm_solver = True,
        debug = True,
    )
    defaults.update(model_and_diffusion_defaults())

    return defaults
```

**Comment by cyz21** [comment]
I have the same question. Who can answer the question? Thank you very much.

**Comment by Saharsh1005** [comment]
Hey @cyz21,
I was able to overcome this error. One needs to set the `dpm_solver=True` after `defaults.update(model_and_diffusion_defaults())`.

So you can do something like:
`args.dpm_solver = True`

Hope this helps!

However, I am not stuck due to CUDA out of memory error, only able to sample and infer one image.

**Comment by cyz21** [comment]
> Hey @cyz21, I was able to overcome this error. One needs to set the `dpm_solver=True` after `defaults.update(model_and_diffusion_defaults())`.
> 
> So you can do something like: `args.dpm_solver = True`
> 
> Hope this helps!
> 
> However, I am not stuck due to CUDA out of memory error, only able to sample and infer one image.

Thank you for your reply! In addition to this, I also have doubts about your initial question. What's the difference between savedmodel_XXXX.pt, optsavedmodel_XXXX.pt, emasavedmodel_XXXX.pt？Which one should I choose to use?Thank you again!

**Comment by Saharsh1005** [comment]
> > Hey @cyz21, I was able to overcome this error. One needs to set the `dpm_solver=True` after `defaults.update(model_and_diffusion_defaults())`.
> > So you can do something like: `args.dpm_solver = True`
> > Hope this helps!
> > However, I am not stuck due to CUDA out of memory error, only able to sample and infer one image.
> 
> Thank you for your reply! In addition to this, I also have doubts about your initial question. What's the difference between savedmodel_XXXX.pt, optsavedmodel_XXXX.pt, emasavedmodel_XXXX.pt？Which one should I choose to use?Thank you again!

You can give the ema or savedmodel in the inference checkpoint path. optmodel gave me error. 
Hope this helps!

**Comment by wzx0720** [comment]
> Hey @cyz21, I was able to overcome this error. One needs to set the after .`dpm_solver=True``defaults.update(model_and_diffusion_defaults())`
> 
> So you can do something like: `args.dpm_solver = True`
> 
> Hope this helps!
> 
> However, I am not stuck due to CUDA out of memory error, only able to sample and infer one image.

  Hey, I have the same question that when I run `segmentation.py`, it only sample and infer 2 images. I wonder how you solving this problem? Thanks a lot!
