### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by alqurri77** [WuJunde/MedSegDiff#56]
Hi;

When I run the script:

python scripts/segmentation_train.py --data_name ISIC --data_dir /tmp/ahmed/isic --out_dir /tmp/ahmed/out --image_size 256 --num_channels 128 --class_cond False --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --noise_schedule linear --rescale_learned_sigmas False --rescale_timesteps False --lr 1e-4 --batch_size 8

I got:

Logging to /tmp/ahmed/out
creating data loader...
creating model and diffusion...
training...
Traceback (most recent call last):
  File "/tmp/ahmed/MedSegDiff-master/scripts/segmentation_train.py", line 110, in <module>
    main()
  File "/tmp/ahmed/MedSegDiff-master/scripts/segmentation_train.py", line 62, in main
    TrainLoop(
  File "/tmp/ahmed/MedSegDiff-master/./guided_diffusion/train_util.py", line 179, in run_loop
    batch, cond, name = next(data_iter)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by TMullerSG** [comment]
remove the final if else from the data loader isicloader.py

**Comment by Saharsh1005** [comment]
In the dataset class (e.g. IRIC), the get-item function returns (image,mask,name). So when you are calling the dataloader object you need to unpack it using 3 variables.

**Comment by yindanping** [comment]
Have you solved this problem?Can we add WeChat for communication?

**Comment by alqurri77** [comment]
Yes. problem solved. Thank you!

**Comment by 602066163** [comment]
你好  我也遇到了这个问题 请问一下怎么解决的

**Comment by 602066163** [comment]
> 这个问题解决了吗？可以加微信交流吗？

> Yes. problem solved. Thank you!

你好 请问一下怎么解决这个问题的

**Comment by 602066163** [comment]
> 你好请问一下怎么解决这个问题的

你好请问一下怎么解决这个问题的

**Comment by 602066163** [comment]
> Yes. problem solved. Thank you!

Hi, I'm having this problem too, can you tell me how to solve it?

**Comment by 602066163** [comment]
> Have you solved this problem?Can we add WeChat for communication?

Hi, I'm having this problem too, can you tell me how to solve it?

**Comment by alqurri77** [comment]
just in ISICDataset, remove name: 
```
if self.mode == 'Training':
            return (img, mask)
            # return (img, mask,name)
        else:
            return (img, mask)#, name)
```

**Comment by yindanping** [comment]
Thank you for your answer.  Would you like to share this code with me? This is my WeChat account. （yyy03090412）

**Comment by 602066163** [comment]
Thank you ，I have solved the problem thank you very much







                       
原始邮件
                       
                     

发件人："yindp"< ***@***.*** &gt;;

发件时间：2023/3/24 11:25

收件人："WuJunde/MedSegDiff"< ***@***.*** &gt;;

抄送人："Matchless"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [WuJunde/MedSegDiff] ValueError: not enough values to unpack(expected 3, got 2) (Issue #56)




 
Thank you for your answer.  Would you like to share this code with me? This is my WeChat account. （yyy03090412）
 
&mdash;
