### ISSUE TITLE
3D segmentation

### ISSUE THREAD

**Issue by asdkd** [WuJunde/MedSegDiff#57]
Hi,

Is MedsegDiff available for 3D segmentation? According to the description in the paper, the model can be trained on the 2D CT images and get good results. I was wondering if it is possible to extend this network to 3D manner?

**Comment by sgc123** [comment]
fllow this question

**Comment by WuJunde** [comment]
yes. in the current version, we take 3d data as a series of 2d slices. it can also be easily adapted to the raw 3d volume by using 3d unet backbone.

**Comment by asdkd** [comment]
Thanks for your response. Have you ever do some experiments using 3D UNet backbone in your proposed pipeline? Maybe it is not as feasible as 2D manner especially for the 3D input with high resolution as 256*256*256. The main problem is it's too heavy to train a 3D condition UNet and a 3D diffusion UNet at the same time, even using high memory gpu A6000 (48GB).

**Comment by WuJunde** [comment]
yes. and I have noticed some follow-up papers have extended it 3D segmentation, like https://arxiv.org/abs/2303.10326. check their work for more details.
