### ISSUE TITLE
With the default configuration in the code, how long does it take to train?

### ISSUE THREAD

**Issue by lixiang007666** [WuJunde/MedSegDiff#58]
I would like to ask how long does it take to train with the default configuration in the code under the condition of a single gpu?

I trained 30+ hours with 3080ti and it's not over yet.

🙂

**Comment by MOZhuai** [comment]
It depend on you, you can stop running when you want to stop. or you can add `--lr_anneal_steps num_of_steps` before running. when i run this code, i set num_of_steps to 100000.

**Comment by MOZhuai** [comment]
Num_of_steps may depend on the batch size.

**Comment by MOZhuai** [comment]
if you use the default configuration, it will not stop.

**Comment by lixiang007666** [comment]
OK, Thanks~
😀
