### ISSUE TITLE
Sample Visualization and Metrics

### ISSUE THREAD

**Issue by jcwang123** [WuJunde/MedSegDiff#6]
We have trained the diffusion model in more than 100,000 steps and sampled the test images.
However, the predictions seem wrong as pixel values vary from 0 to tens instead of 0,1.
How to obtain the final segmentation mask?
![0000015_output](https://user-images.githubusercontent.com/37990976/206643896-e718eefd-f459-421a-bd4b-113f5f5d8070.jpg)

**Comment by jcwang123** [comment]
I tried to visualize the prediction in the heatmap and it is like this:
![tmp](https://user-images.githubusercontent.com/37990976/206644513-6e8ef4fb-e5b2-433e-a837-247556d54da7.jpg)

**Comment by WuJunde** [comment]
It should be 0-1. Have you modified the code? Is it the prediction saved by the scource code in ./results fold?

**Comment by jcwang123** [comment]
I have not modified the code. I will check the details. Thanks.

**Comment by ZhouCX117** [comment]
@jcwang123 Hi, have you solved this question? I met the same problem.

**Comment by jessie-chen99** [comment]
> I have not modified the code. I will check the details. Thanks.
Hi, did you figure out this problem? I have the same problem in visualization.

**Comment by jaceqin** [comment]
> > I have not modified the code. I will check the details. Thanks.
> 
> @jcwang123 Hi, did you figure out this problem? I have the same problem in visualization.

Did you figure out this problem?

**Comment by jaceqin** [comment]
> > I have not modified the code. I will check the details. Thanks.
> 
> @jcwang123 Hi, did you figure out this problem? I have the same problem in visualization.
Did you figure out this problem?
