### ISSUE TITLE
Why the results look good, but the dice are very low？

### ISSUE THREAD

**Issue by jaceqin** [WuJunde/MedSegDiff#60]
![Validation_340_slice_115_output0](https://user-images.githubusercontent.com/108056546/226185217-1885060a-34fb-492b-8b0b-0d6af36088d9.jpg)
![Validation_369_slice_110_output4](https://user-images.githubusercontent.com/108056546/226185219-47c415e5-dd49-45ff-9498-f51d68036738.jpg)

The above is the result of my sampling, the surface looks good, but I used medpy's dc for testing, this score has been around 0.1.
![ec86ab0a26fac6feae96affa1003636](https://user-images.githubusercontent.com/108056546/226185315-cd1b0915-8aed-4df9-a2a5-044b24b34561.png)

**Comment by DBook111** [comment]
算错了吧

**Comment by saisusmitha** [comment]
@jaceqin can you please tell me where and how (the code) you included to find these scores - also how much data did you train and test as part of the training data that should be used for validation i.r finding scores? The original data is 3d 240x240x155 how did you use it for this code when I used BRATSDataset3D and saved the input images as png it looked wrong. Kindly clear these.
