### ISSUE TITLE
Some doubts about saved model dict.

### ISSUE THREAD

**Issue by lixiang007666** [WuJunde/MedSegDiff#61]
We save three types of model dicts, including:

- emasavedmodelxxx.pt
- optsavedmodelxxx.pt
- savedmodelxxx.pt

What do they represent?
How to test to see which is better?
😀

**Comment by yao-yu1999** [comment]
请问你解决了吗？我也是保存了三个模型，不知道分别代表着什么意思

**Comment by theneao** [comment]
ema权重平移的，opt是优化器的参数不是整个模型的，测试用普通的就行,具体参考DDPM代码
