### ISSUE TITLE
关于您提供的原代码出现的一些问题

### ISSUE THREAD

**Issue by NickWang1122** [WuJunde/MedSegDiff#62]
我按照您的代码，使用了BraTS2020数据集，发现bratsloader.py代码可能存在问题：
1.class BRATSDataset(torch.utils.data.Dataset)和class BRATSDataset3D(torch.utils.data.Dataset)命名可能反了，在class BRATSDataset(torch.utils.data.Dataset)下才是将数据3D送入网络而class BRATSDataset3D(torch.utils.data.Dataset)是将每个模态的切片拼在一起后分批送入网络。
2.class BRATSDataset的transforms有问题，transforms.Resize((args.image_size, args.image_size)应该是resize图像的W和H,而您resize了深度维

**Comment by NickWang1122** [comment]
还有这行代码，image = image[..., 8:-8, 8:-8]  您的本意应该是裁剪W和H，但是却裁剪了H和D，应该改为  image = image[:, 8:-8, 8:-8, :]

**Comment by WuJunde** [comment]
They are correct, no mistake
