### ISSUE TITLE
code for the scores [ HD95, Jaccard Index ]?

### ISSUE THREAD

**Issue by saisusmitha** [WuJunde/MedSegDiff#63]
kindly mention where did you extract the dice score, jaccard index, hd95 score and all.

**Comment by saisusmitha** [comment]
@WuJunde kindly help me with this

**Comment by WuJunde** [comment]
hi, I provide an example evaluation code of dice and iou(jaccard) in script/segmentation_env.py. hd95 implementation can be easily found online if you need.
