### ISSUE TITLE
infinite loop in segmentation_sample.py 

### ISSUE THREAD

**Issue by alqurri77** [WuJunde/MedSegDiff#65]
Hi;

I notice segmentation_sample.py  keep running because **all_images** in below loop always empty. 
Where does **all_images** supposed to get incremented.

`while len(all_images) * args.batch_size < args.num_samples:`

**Comment by WuJunde** [comment]
check this issue: https://github.com/WuJunde/MedSegDiff/issues/28

**Comment by alqurri77** [comment]
Thank you!
