### ISSUE TITLE
single GPU to train

### ISSUE THREAD

**Issue by Miraclecb** [WuJunde/MedSegDiff#66]
if I  want to train & sample in single GPU，How can i fix the dist_util.py & train_util.py? Thanks!

**Comment by WuJunde** [comment]
what do you mean? It can work normally on single GPU just running the default command. What' s the wrong message?

**Comment by Miraclecb** [comment]
已经收到了

**Comment by Miraclecb** [comment]
Thanks for your reply. I have run the single GPU training, but the variable "name" in line 179 of train_util.py can't seem to be found (although it works after I commented it out) 
wrong message:
ValueError：Not enough values to unpack（expected 3 got 2）

**Comment by WuJunde** [comment]
this error has nothing to do with GPU, if you need name parameter, just add one variable to receive it. if you do not need name parameter, you can just comment it out.
