### ISSUE TITLE
DPM-Solver Memory Problem

### ISSUE THREAD

**Issue by jaceqin** [WuJunde/MedSegDiff#69]
Why I using DPM-Solver to sample, the memory usage of GPU improves 2GB.

**Comment by AndrewChiyz** [comment]
I got OOM when using the '--dpm_solver True' option. The GPU memory is 24G.

**Comment by xupinggl** [comment]
I meet the same question. @AndrewChiyz Have you solved it yet?

**Comment by WuJunde** [comment]
it's a known bug caused by pytorch version. using pytorch 1.8 would be fine.

**Comment by PapaMadeleine2022** [comment]
> it's a known bug caused by pytorch version. using pytorch 1.8 would be fine.

I use A30 GPU and only can use torch>=1.13.0.  还有别的解决办法吗

**Comment by xupinggl** [comment]
您好，您的邮件我已收到，我会尽快回复的，谢谢！

**Comment by PapaMadeleine2022** [comment]
> it's a known bug caused by pytorch version. using pytorch 1.8 would be fine.

我试了 torch1.8.0也不行啊 GPU显存还是会爆掉

**Comment by PapaMadeleine2022** [comment]
need help!!  @WuJunde
