### ISSUE TITLE
Mistakes in training on my own training set

### ISSUE THREAD

**Issue by Learnshui** [WuJunde/MedSegDiff#7]
<img width="511" alt="image" src="https://user-images.githubusercontent.com/63939745/206948733-cdb729c5-104b-4b5a-a1e0-5e8beeb80445.png">
when changed to [hs[2],hs[5],hs[8],hs[11]],another error continues to occur,I want to know how to modify it，Thanks！

**Comment by WuJunde** [comment]
check this one: https://github.com/WuJunde/MedSegDiff/issues/8
