### ISSUE TITLE
Question about: self.highway_forward(c, [hs[3],hs[6],hs[9],hs[12]]) ?

### ISSUE THREAD

**Issue by heikeyuhuajia** [WuJunde/MedSegDiff#74]
Hi, I found this line "uemb, cal = self.highway_forward(c, [hs[3],hs[6],hs[9],hs[12]])" in unet.py, but there is no "hs[12]". Our dataset images are binary 256*256 in size and the labels are 1*256*256.

**Comment by WuJunde** [comment]
use the default parameters first, it will work under default setting. these hyper-parameters should be changed with the different model settings, but I haven't fixed it yet.

**Comment by WuJunde** [comment]
check this issue: https://github.com/WuJunde/MedSegDiff/issues/8

**Comment by heikeyuhuajia** [comment]
Thank you very much for your answer. The code is already running!

**Comment by QijingGJ** [comment]
> Thank you very much for your answer. The code is already running!

hello, I have been confused for a long time, could you help me? Why is one of the output called ‘cal’ of self.highway_forward calculate mse with the target mode? What exactly is the function of self.highway_forward ？

Thank you very much for your help！
