### ISSUE TITLE
求指教，ISIC数据集中的csv文件在哪里下载？

### ISSUE THREAD

**Issue by William9Baker** [WuJunde/MedSegDiff#76]
想请问下，ISIC数据集中的 “ISBI2016_ISIC_Part3B_Training_GroundTruth.csv” 这个文件在哪里下载？谢谢！

**Comment by Kong-hub** [comment]
点开链接，最后一行

**Comment by William9Baker** [comment]
> 点开链接，最后一行

请问，是哪个链接？ISIC Challenge官网链接吗？里面没有找到唉

**Comment by Kong-hub** [comment]
下载3B的就行

**Comment by William9Baker** [comment]
> 下载3B的就行

请问下，3B具体是什么呀？不知道这个csv在哪里下载，想看下数据集加载的格式

**Comment by WuJunde** [comment]
csv files have been provided in ./data
