### ISSUE TITLE
If micro size is smaller than batch size, then it just run the micro size?

### ISSUE THREAD

**Issue by MOZhuai** [WuJunde/MedSegDiff#77]
In the function `forward_backward(self, batch, cond)` of file `guided_diffusion/train_util.py`, after train on the first micro batch, the project directly return the sample `return sample`.
In this code, `return` is in side of the `for` loop.
https://github.com/WuJunde/MedSegDiff/blob/e0e4d0aede856e4c7352eb356a67c74f5b3855ce/guided_diffusion/train_util.py#L215-L260

**Comment by WuJunde** [comment]
In the current implementation micro-batch == batch size, you can change the setting for your needs.
