### ISSUE TITLE
Run on my own dataset

### ISSUE THREAD

**Issue by DWBSIC** [WuJunde/MedSegDiff#78]
Run on my own dataset
It is simple to run MedSegDiff on the other datasets. Just write another data loader file following  ./guided_diffusion/isicloader.py or  ./guided_diffusion/bratsloader.py. 

Question 1: How should I modify the values returned by the dataloder (based on these two example datasets) to ensure the input into this MedSegDiff model?

Question 2: How should the final train or sample good results be output by evaluation metrics (e.g. Dice IoU DSC (%) SEN (%) PPV (%))?

Thanks to the authors for their help and to the good people of the community. 
If have community comrades to discuss, please send contact information to my email address, personal home page details see email address.

Run on my own dataset
It is simple to run MedSegDiff on the other datasets. Just write another data loader file following  ./guided_diffusion/isicloader.py or  ./guided_diffusion/bratsloader.py. 

问题1：请问我应该如何修改dataloder返回的值（根据这俩个举例的数据集），以保证输入进这个MedSegDiff模型里面？

问题2：最终train或者sample好的结果应当如何通过评价指标（例如Dice IoU DSC (%) SEN (%) PPV (%)）将其输出出来？

感谢作者的帮助，感谢社区好心人的帮助。
如有社区同志讨论，请发送联系方式到我的邮箱，个人主页详见邮箱地址。

**Comment by heikeyuhuajia** [comment]
> Run on my own dataset It is simple to run MedSegDiff on the other datasets. Just write another data loader file following ./guided_diffusion/isicloader.py or ./guided_diffusion/bratsloader.py.
> 
> Question 1: How should I modify the values returned by the dataloder (based on these two example datasets) to ensure the input into this MedSegDiff model?
> 
> Question 2: How should the final train or sample good results be output by evaluation metrics (e.g. Dice IoU DSC (%) SEN (%) PPV (%))?
> 
> Thanks to the authors for their help and to the good people of the community. If have community comrades to discuss, please send contact information to my email address, personal home page details see email address.
> 
> Run on my own dataset It is simple to run MedSegDiff on the other datasets. Just write another data loader file following ./guided_diffusion/isicloader.py or ./guided_diffusion/bratsloader.py.
> 
> 问题1：请问我应该如何修改dataloder返回的值（根据这俩个举例的数据集），以保证输入进这个MedSegDiff模型里面？
> 
> 问题2：最终train或者sample好的结果应当如何通过评价指标（例如Dice IoU DSC (%) SEN (%) PPV (%)）将其输出出来？
> 
> 感谢作者的帮助，感谢社区好心人的帮助。 如有社区同志讨论，请发送联系方式到我的邮箱，个人主页详见邮箱地址。

对于您第一个问题：作者在其他issue说只要保证你的dataset能返回**_（图像，掩码，名称）_**就可以。

**Comment by heikeyuhuajia** [comment]
> > > Run on my own dataset It is simple to run MedSegDiff on the other datasets. Just write another data loader file following ./guided_diffusion/isicloader.py or ./guided_diffusion/bratsloader.py.
> > > Question 1: How should I modify the values returned by the dataloder (based on these two example datasets) to ensure the input into this MedSegDiff model?
> > > Question 2: How should the final train or sample good results be output by evaluation metrics (e.g. Dice IoU DSC (%) SEN (%) PPV (%))?
> > > Thanks to the authors for their help and to the good people of the community. If have community comrades to discuss, please send contact information to my email address, personal home page details see email address.
> > > Run on my own dataset It is simple to run MedSegDiff on the other datasets. Just write another data loader file following ./guided_diffusion/isicloader.py or ./guided_diffusion/bratsloader.py.
> > > 问题1：请问我应该如何修改dataloder返回的值（根据这俩个举例的数据集），以保证输入进这个MedSegDiff模型里面？
> > > 问题2：最终train或者sample好的结果应当如何通过评价指标（例如Dice IoU DSC (%) SEN (%) PPV (%)）将其输出出来？
> > > 感谢作者的帮助，感谢社区好心人的帮助。 如有社区同志讨论，请发送联系方式到我的邮箱，个人主页详见邮箱地址。
> > 
> > 
> > 对于您第一个问题：作者在其他issue说只要保证你的dataset能返回**(图像，掩码，名称)**就可以。
> 
> 请问您复现出评价指标的数据了吗，是如何评估分割的结果呢

我用在了新的数据集上，没有用他的数据集。

**Comment by theneao** [comment]
请问运行在你们的数据集上效果如何？在我的数据集上效果比正常的U-Net效果都要差很多，你们有这种情况吗？你们知道这主要是由于什么造成的吗？

**Comment by heikeyuhuajia** [comment]
> 
V2版本在我们数据集上 iou是0.65左右，但是可视化结果还蛮好的，我也正在找问题。

**Comment by songhuaqinggg** [comment]
> > 
> 
> V2版本在我们数据集上 iou是0.65左右，但是可视化结果还蛮好的，我也正在找问题。

请问您最后的loss大概多少啊

**Comment by heikeyuhuajia** [comment]
我的 loss 大概在 0.003 左右吧
