### ISSUE TITLE
  关于ISCI数据集实验结果

### ISSUE THREAD

**Issue by knavecoder** [WuJunde/MedSegDiff#79]
我按照作者给出的超参数，训练数据集得到的效果很差，我想请问你们得到的结果是什么样子的

**Comment by knavecoder** [comment]
![image](https://user-images.githubusercontent.com/66984677/231162201-99693de6-d499-45d0-b865-bf990d8a6ef5.png)

**Comment by zzt93931** [comment]
> 我按照作者给出的超参数，训练数据集得到的效果很差，我想请问你们得到的结果是什么样子的

我也是得到了很差的效果，dice只有69%

**Comment by YonghanLU** [comment]
我的结果挺好的，Dice大概在86.7左右

**Comment by zzt93931** [comment]
> 我的结果挺好的，Dice大概在86.7左右

可以加微信交流一下嘛

**Comment by YonghanLU** [comment]
可以，DawnSh1m1ly，这是微信号

**Comment by DWBSIC** [comment]
> 

请问您这个训练模型多少轮呢

**Comment by DWBSIC** [comment]
> ![image](https://user-images.githubusercontent.com/66984677/231162201-99693de6-d499-45d0-b865-bf990d8a6ef5.png)


请问您这个训练模型多少轮呢

**Comment by knavecoder** [comment]
> > ![image](https://user-images.githubusercontent.com/66984677/231162201-99693de6-d499-45d0-b865-bf990d8a6ef5.png)
> 
> 请问您这个训练模型多少轮呢

12W

**Comment by algorithmlixuan** [comment]
dice 87.3% batchsize 24

**Comment by Devil-Ideal** [comment]
![image](https://github.com/WuJunde/MedSegDiff/assets/73993506/5829058f-a82d-4e29-8d82-020628bafa66)
by default

**Comment by Devil-Ideal** [comment]
> ![image](https://user-images.githubusercontent.com/73993506/248440420-5829058f-a82d-4e29-8d82-020628bafa66.png) by default

20w iterations
