### ISSUE TITLE
Code Training Problem

### ISSUE THREAD

**Issue by litlepeng** [WuJunde/MedSegDiff#8]
Depending on the author, after downloading the dataset and running the code, the following issues arise。
<img width="1695" alt="image" src="https://user-images.githubusercontent.com/29767470/207275452-128242fd-996a-4e68-98a4-0457121ae864.png">
Then after debug, we found that the length of hs is 12, so we changed the index to 11 and ran it again, which caused the following problems
<img width="1718" alt="image" src="https://user-images.githubusercontent.com/29767470/207275877-14bd3f02-69bf-4124-842c-3f5a53783899.png">
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/29767470/207275907-6fd26155-333f-4cb7-88e7-ab82c2fd4b37.png">
Please help the author to answer, thank you。

**Comment by WuJunde** [comment]
What's your parameters? Try following parameters: --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1. It should work well. There may have some settings in the code need to be modified if you want to run with different parameters. I will update it in the next version.

**Comment by litlepeng** [comment]
> What's your parameters? Try following parameters: --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1. It should work well. There may have some settings in the code need to be modified if you want to run with different parameters. I will update it in the next version.
Thank you very much

**Comment by litlepeng** [comment]
Thank you very much
