### ISSUE TITLE
There is a wrong in data_csv index

### ISSUE THREAD

**Issue by sunshinelike** [WuJunde/MedSegDiff#86]
<img width="750" alt="ad5efb19ff1c5d00bfe1b3d83ebd9fe" src="https://user-images.githubusercontent.com/29997402/232415117-54a01564-5532-4b9e-bdca-40798fe1490c.png">
<img width="605" alt="968c0a90eecef9b35134c2569322c50" src="https://user-images.githubusercontent.com/29997402/232415178-d0d7057b-025d-4414-9e9a-52a061e2dd6a.png">

**Comment by WuJunde** [comment]
yes. sorry for leading the misunderstanding. the difference between part1 and 3b is that part1 is only for segmentation, and 3b is for segmentation and diagnosis. I switch it from 3b to 1 in version 2, but both will work fine. you can download part1 data and use this csv anyway.

**Comment by sunshinelike** [comment]
OK, thank you, got, if you could update the readme and file name, that would be better for understanding. And could you share the csv maker script?

**Comment by WuJunde** [comment]
sure

`import os
import pandas as pd

path = '../../data/isic/isic2016'
train_data_dir = 'ISBI2016_ISIC_Part1_Training_Data'
train_gt_dir = 'ISBI2016_ISIC_Part1_Training_GroundTruth'
csv_path_train = '../ISBI2016_ISIC_Part3B_Training_GroundTruth.csv'

col_names = ['img','seg']
df = pd.DataFrame()

for (root,dirs,files) in os.walk(os.path.join(path,train_data_dir), topdown=True):
    for name in files:
        preind = name.split('.')[0]
        segname = preind + '_Segmentation.png'
        segpath = os.path.join( train_gt_dir, segname)
        imgpath = os.path.join( train_data_dir, name)
        data = pd.DataFrame([[imgpath,segpath]], columns = col_names)
        df = df.append(data, ignore_index=True)
df.to_csv(csv_path_train)`

**Comment by WuJunde** [comment]
download training ground truth, which is the segmentation

**Comment by sunshinelike** [comment]
> download training ground truth, which is the segmentation
Oh, I see. Thank you very much, best wishes.

**Comment by sunshinelike** [comment]
> download training ground truth, which is the segmentation
oh,I see. Thank you very much,
