### ISSUE TITLE
sample running error

### ISSUE THREAD

**Issue by litlepeng** [WuJunde/MedSegDiff#9]
Error using official run mode.

mentation_sample.py --data_dir /home/yp/diskdata/workspace/medsegdiff/dataset/ISIC --model_path /home/yp/diskdata/workspace/medsegdiff/results/savedmodel020000.pt  --image_size 256 --num_channels 128 --class_cond False --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --noise_schedule linear --rescale_learned_sigmas False --rescale_timesteps False --num_ensemble 5

**Comment by litlepeng** [comment]
The error message is as follows：
Logging to ./results/
creating model and diffusion...
Traceback (most recent call last):
File "/home/yp/diskdata/workspace/medsegdiff/scripts/segmentation_sample.py", line 138, in <module>
main()
File "/home/yp/diskdata/workspace/medsegdiff/scripts/segmentation_sample.py", line 83, in main
b, m, path = next(data)  # should return an image from the dataloader "data"
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by WuJunde** [comment]
you return two values in test dataloader, and expect to return three. If you don't have mask for your test set, just return (img, img, path), it will not effect the sampling.

**Comment by litlepeng** [comment]
I am now using the ISBI2016 dataset you provided. In the test set, we only have the original image and the split image, so now we have problems returning. Let me replace that with the Brain dataset. thank you

**Comment by WuJunde** [comment]
> I am now using the ISBI2016 dataset you provided. In the test set, we only have the original image and the split image, so now we have problems returning. Let me replace that with the Brain dataset. thank you

What's split image. It should work well on ISIC2016 dataset. I mean even you don't have GT, you can simply return (img,img,name) to make it run. Moreover, I remember ISIC provides the test ground-truth.
