### ISSUE TITLE
The out_channels of the model

### ISSUE THREAD

**Issue by YonghanLU** [WuJunde/MedSegDiff#91]
Why the out_channels of the model is 2 ? I do not understand , the output for labels should be 1 channel if not learn sigma.

**Comment by WuJunde** [comment]
check this issue: https://github.com/WuJunde/MedSegDiff/issues/3

**Comment by YonghanLU** [comment]
Thanks , but in the **'def diffusion_defaults()'**  of your code , the learn_sigma is False , then the model_var_type will be gd.ModelVarType.FIXED_LARGE at **'def create_gaussian_diffusion'** in script.util.

**Comment by YonghanLU** [comment]
Should I change learn_sigma to True ? When False , I found it also works , but I think this may be redundant,

**Comment by YonghanLU** [comment]
Sorry , I review your README , I found I ignored "learn_sigma True" .You are right , thanks a lot again.
