### ISSUE TITLE
About the problems in the sampling process

### ISSUE THREAD

**Issue by heikeyuhuajia** [WuJunde/MedSegDiff#96]
Thank you for your work. I checked the previous issues and did not find the answer. Did not modify your structure. I had the following problems with the SAMPLES process:
1. Implementation Code：
`python scripts/segmentation_sample.py --model_path savedmodel080000.pt --image_size 256 --num_channels 128 --class_cond False --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --dpm_solver False  --noise_schedule linear --rescale_learned_sigmas False --rescale_timesteps False --num_ensemble 5 `
The time to sample a graph is as follows：
![image](https://user-images.githubusercontent.com/101233597/234494638-005605eb-326c-457d-9094-55d641c468a2.png)
**_Question1_** : My test set has 1500 images of size 256, and the sampling time is over 24 hours and still not finished. Is this normal?
Also, the inference result of this setup is as follows：
<img width="744" alt="image" src="https://user-images.githubusercontent.com/101233597/234494893-3ebbc28d-5d1e-4192-af18-774fd703c7e9.png">
On the left is the predicted image, and on the right is the Ground Truth.

**_Question2_** : When setting `--diffusion_steps 50 --dpm_solver True`, an error occurred：

> Logging to /home/wyuan/cyberpunk/MedSegDiff_Own/vaihingen_dpmsolver_step50
> creating model and diffusion...
> sampling...
> time for 1 sample 5473.63623046875
> /home/wyuan/cyberpunk/MedSegDiff_Own/scripts/segmentation_sample.py:137: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
>   co = th.tensor(cal_out)                              
> time for 1 sample 2923.864990234375
> time for 1 sample 2950.60595703125
> time for 1 sample 2944.36962890625
> time for 1 sample 2952.309814453125
> sampling...
> time for 1 sample 2978.218505859375
> time for 1 sample 2955.224853515625
> time for 1 sample 2948.672607421875
> time for 1 sample 2967.96337890625
> time for 1 sample 2954.19482421875
> sampling...
> Traceback (most recent call last):
>   File "/home/wyuan/cyberpunk/MedSegDiff_Own/scripts/segmentation_sample.py", line 201, in <module>
>     main()
>   File "/home/wyuan/cyberpunk/MedSegDiff_Own/scripts/segmentation_sample.py", line 125, in main
>     sample, x_noisy, org, cal, cal_out = sample_fn(
>   File "/home/wyuan/cyberpunk/MedSegDiff_Own/./guided_diffusion/gaussian_diffusion.py", line 545, in p_sample_loop_known
>     sample, cal = dpm_solver.sample(
>   File "/home/wyuan/cyberpunk/MedSegDiff_Own/./guided_diffusion/dpm_solver.py", line 1193, in sample
>     out = self.model(torch.cat((self.img,x), dim=1).to(dtype = torch.float), t)
>   File "/home/wyuan/cyberpunk/MedSegDiff_Own/./guided_diffusion/dpm_solver.py", line 370, in <lambda>
>     self.model = lambda x, t: model_fn(x, t.expand((x.shape[0])))
>   File "/home/wyuan/cyberpunk/MedSegDiff_Own/./guided_diffusion/dpm_solver.py", line 283, in model_fn
>     return noise_pred_fn(x, t_continuous)
>   File "/home/wyuan/cyberpunk/MedSegDiff_Own/./guided_diffusion/dpm_solver.py", line 254, in noise_pred_fn
>     output = model(x, t_input, **model_kwargs)
>   File "/home/wyuan/anaconda3/envs/meddiff/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/wyuan/cyberpunk/MedSegDiff_Own/./guided_diffusion/unet.py", line 1091, in forward
>     h = module(h, emb)
>   File "/home/wyuan/anaconda3/envs/meddiff/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/wyuan/cyberpunk/MedSegDiff_Own/./guided_diffusion/unet.py", line 84, in forward
>     x = layer(x, emb)
>   File "/home/wyuan/anaconda3/envs/meddiff/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/wyuan/cyberpunk/MedSegDiff_Own/./guided_diffusion/unet.py", line 297, in forward
>     return checkpoint(
>   File "/home/wyuan/cyberpunk/MedSegDiff_Own/./guided_diffusion/nn.py", line 142, in checkpoint
>     return func(*inputs)
>   File "/home/wyuan/cyberpunk/MedSegDiff_Own/./guided_diffusion/unet.py", line 321, in _forward
>     return self.skip_connection(x) + h
>   File "/home/wyuan/anaconda3/envs/meddiff/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/wyuan/anaconda3/envs/meddiff/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
>     return self._conv_forward(input, self.weight, self.bias)
>   File "/home/wyuan/anaconda3/envs/meddiff/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
>     return F.conv2d(input, weight, bias, self.stride,
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 23.69 GiB total capacity; 22.32 GiB already allocated; 31.81 MiB free; 22.37 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**_Question3_** : In addition, the sampled results are as follows, which do not seem to be as good as the above results.
<img width="335" alt="image" src="https://user-images.githubusercontent.com/101233597/234495632-f7d95b8e-e412-4f13-9617-2cb1675756dc.png">
Does setting **dpmsolver** and **steps** affect the model's inferential performance?
I am currently following your work to improve Meddiff for other areas and look forward to hearing from you!

**Comment by WuJunde** [comment]
yes, the inference time is long, and dpmsolver will compromise the performance. Q2 is a known bug that dim-solver can only  run with PyTorch 1.8. I am still working on that.
